name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - run: |
        find .
        pwd

    - name: Install dependencies
      run: npm install
      working-directory: ./ui

    - name: Build
      run: |
        pwd
        npm run build

      working-directory: ./ui

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ./ui/build
        CLEAN: true
